export default [
  "latte",
  "frappe",
  "macchiato",
  "mocha",
  "rosepine-dawn",
  "rosepine-moon",
  "rosepine",
  "evergarden-spring",
  "evergarden-summer",
  "evergarden-fall",
  "evergarden-winter",
  "light",
  "dark",
];